<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'name' => 'LED Recessed / Surface Panel Light (HIKARI AFG)',
                'category' => 'Lighting',
                'price' => 29.90,
                'original_price' => 36.00,
                'rating' => 5,
                'image' => '/pdf-images/page-019-1.jpg',
                'description' => 'SIRIM-approved LED panel lighting for office, hotel, and residential use. Available in round/square and recessed/surface variants.',
                'is_sale' => true,
                'brand' => 'HIKARI',
                'available_at' => ['hq', 'kuantan', 'tas', 'batu', 'chukai'],
                'variants' => ['Recessed Round', 'Recessed Square', 'Surface Round', 'Surface Square'],
                'colors' => ['Daylight 6500K', 'Cool White 4000K', 'Warm White 3000K'],
                'sizes' => ['4 inch', '6 inch', '8 inch', '12 inch'],
                'choices' => ['Indoor Use', 'Non-Dimmable', 'Open Fitting Compatible'],
                'model_codes' => ['AFG-4DLR-12L', 'AFG-6DLR-18L', 'AFG-24SR', 'AFG-24SS'],
                'inventory_matrix' => [],
            ],
            [
                'name' => 'LED Flood Light (HIKARI AFG-FL Series)',
                'category' => 'Lighting',
                'price' => 89.00,
                'rating' => 4,
                'image' => '/pdf-images/page-023-1.jpg',
                'description' => 'IP66 waterproof flood light for warehouse, workshop, garden, and outdoor projects.',
                'is_new' => true,
                'brand' => 'HIKARI',
                'available_at' => ['hq', 'balok', 'batu', 'chukai', 'tas'],
                'variants' => ['AFG-FL-50', 'AFG-FL-100', 'AFG-FL-150', 'AFG-FL-200'],
                'colors' => ['Daylight', 'Warm White'],
                'sizes' => ['185 x 220 x 30mm', '240 x 275 x 30mm', '275 x 295 x 30mm', '335 x 350 x 30mm'],
                'types' => ['IP66 Outdoor Floodlight'],
                'choices' => ['PF 0.9', '100-240V'],
                'inventory_matrix' => [],
            ],
            [
                'name' => 'LED T8 Tube Glass (G13 Cap)',
                'category' => 'Lighting',
                'price' => 18.00,
                'original_price' => 22.00,
                'rating' => 5,
                'image' => '/pdf-images/page-025-1.jpg',
                'description' => 'Premium quality indoor LED T8 tube with multiple wattages and color temperatures.',
                'is_sale' => true,
                'brand' => 'HIKARI',
                'available_at' => ['hq', 'kuantan', 'tas', 'balok', 'batu', 'chukai'],
                'variants' => ['AFG-10TD', 'AFG-20TD', 'AFG-22TD', 'AFG-22TC', 'AFG-22TW', 'AFG-32TD'],
                'colors' => ['Daylight', 'Cool White', 'Warm White'],
                'lengths' => ['28 x 602mm', '28 x 1212mm'],
                'types' => ['G13 Glass Tube'],
                'inventory_matrix' => [],
            ],
            [
                'name' => 'GI Coated / Water-Tight Flexible Conduit',
                'category' => 'Cables',
                'price' => 35.00,
                'rating' => 5,
                'image' => '/pdf-images/page-029-1.jpg',
                'description' => 'G.I inner + PVC outer coated conduit for moist and harsh environments with water-tight options.',
                'is_new' => true,
                'brand' => 'PVC LINK',
                'available_at' => ['hq', 'balok', 'chukai'],
                'variants' => ['LSE', 'MPCFC04', 'MPCFC05', 'MPCFC06', 'MPCFC10', 'MPCFC12', 'MPCFC14', 'MPCFC20', 'PBA206714'],
                'sizes' => ['1/2"', '5/8"', '3/4"', '1"', '1-1/4"', '1-1/2"', '2"'],
                'lengths' => ['15m', '20m', '30m'],
                'choices' => ['IP66 Water-Tight Option'],
                'inventory_matrix' => [],
            ],
            [
                'name' => 'LV Armoured / Non-Armoured Copper Cable',
                'category' => 'Cables',
                'price' => 480.00,
                'rating' => 5,
                'image' => '/pdf-images/page-056-1.jpg',
                'description' => 'Project-grade LV cable range including PVC/SWA/PVC and XLPE/SWA/PVC for industrial and JKR applications.',
                'brand' => 'Mega Kabel',
                'available_at' => ['hq', 'kuantan', 'balok', 'batu', 'chukai'],
                'variants' => ['PVC/SWA/PVC (PSP)', 'PVC/PVC (Non-Armoured)', 'XLPE/SWA/PVC (XSP)', 'XLPE/PVC'],
                'sizes' => ['1.5', '2.5', '4', '6', '10', '16', '25', '35', '50', '70', '95', '120', '150', '185', '240', '300', '500', '630'],
                'choices' => ['2 Core', '3 Core', '4 Core', 'JKR Certified Options', 'SIRIM Range'],
                'inventory_matrix' => [],
            ],
            [
                'name' => 'SIRIM House Cable (90m/coil)',
                'category' => 'Cables',
                'price' => 168.00,
                'rating' => 4,
                'image' => '/pdf-images/page-061-1.jpg',
                'description' => 'Single-core SIRIM-certified house wiring cable available in multiple colours and sizes.',
                'brand' => 'Cable Link',
                'available_at' => ['hq', 'kuantan', 'tas', 'batu'],
                'sizes' => ['1.5mm', '2.5mm', '4mm', '6mm', '10mm', '16mm', '25mm'],
                'colors' => ['Black', 'Red', 'Green', 'Yellow', 'Blue', 'White'],
                'choices' => ['90m/coil', 'SIRIM Certified'],
                'inventory_matrix' => [],
            ],
            [
                'name' => 'Flush Switch Series (Residential & Commercial)',
                'category' => 'Switches',
                'price' => 12.90,
                'rating' => 4,
                'image' => '/pdf-images/page-070-1.png',
                'description' => 'Complete flush switch assortment for homes and projects including 1 to 5 gang options.',
                'brand' => 'Schneider Electric',
                'available_at' => ['hq', 'kuantan', 'tas', 'balok', 'batu', 'chukai'],
                'variants' => ['1 Gang 1 Way', '1 Gang 2 Way', 'Intermediate', '2 Gang 1 Way', '2 Gang 2 Way', '3 Gang 1 Way', '3 Gang 2 Way', '4 Gang 1 Way', '4 Gang 2 Way', 'Bell Switch', 'Press Switch (Auto Gate)'],
                'types' => ['AvatarOn', 'Zencelo', 'Vivace', 'Pieno', 'Affle Plus', 'Metal Clad'],
                'colors' => ['White', 'Silver Satin', 'Silver Bronze', 'Dark Grey', 'Wine Gold', 'Matte Black', 'Light Wood', 'Dark Wood'],
                'inventory_matrix' => [],
            ],
            [
                'name' => 'ELCB / RCCB Protection Series',
                'category' => 'Distribution Boards',
                'price' => 135.00,
                'rating' => 5,
                'image' => '/pdf-images/page-094-1.png',
                'description' => 'Earth leakage protection range with multiple pole, sensitivity, and type selections.',
                'brand' => 'Schneider Electric',
                'available_at' => ['hq', 'kuantan', 'balok', 'batu', 'chukai'],
                'sizes' => ['25A', '40A', '63A', '100A'],
                'types' => ['2 Pole', '4 Pole', 'Type A', 'Type AC'],
                'choices' => ['10mA', '30mA', '100mA', '300mA Trip Sensitivity'],
                'inventory_matrix' => [],
            ],
            [
                'name' => 'MCB / MCCB / Contactor & TOR Range',
                'category' => 'Distribution Boards',
                'price' => 49.90,
                'rating' => 5,
                'image' => '/pdf-images/page-096-1.png',
                'description' => 'Comprehensive breaker and motor control lineup for residential to heavy-duty industrial systems.',
                'brand' => 'ABB',
                'available_at' => ['hq', 'kuantan', 'balok', 'batu', 'chukai', 'tas'],
                'variants' => ['MCB 6A-63A', 'MCCB 32A-1600A', 'Contactor 9A-300A', 'Thermal Overload Relay'],
                'types' => ['Type B', 'Type C', '1P/2P/3P', '3P/4P'],
                'choices' => ['6kA', '10kA', '240V', '415V'],
                'inventory_matrix' => [],
            ],
            [
                'name' => 'PVC Conduit & Accessories Kit',
                'category' => 'Cables',
                'price' => 5.80,
                'rating' => 4,
                'image' => '/pdf-images/page-040-1.jpg',
                'description' => 'PVC accessories set including socket, saddles, reducers, inspection parts, and circular end boxes.',
                'brand' => 'Fighter',
                'available_at' => ['hq', 'kuantan', 'tas', 'balok', 'batu', 'chukai'],
                'variants' => ['Socket', 'Bar Saddle', 'Clip Saddle', 'Reducer', 'Female Adapter', 'Inspection Tee', 'Inspection Elbow', 'Inspection Bend', 'Circular 1/2/3/4 Way Box'],
                'colors' => ['White', 'Orange', 'Black'],
                'sizes' => ['20mm', '22mm', '25mm', '32mm', '40mm', '50mm', '100mm', '150mm'],
                'inventory_matrix' => [],
            ],
            [
                'name' => 'GI Conduit Pipe (MS61386 / BS4568)',
                'category' => 'Cables',
                'price' => 32.00,
                'rating' => 5,
                'image' => '/pdf-images/page-041-1.jpg',
                'description' => 'Galvanized conduit pipes with SIRIM/JKR options for project and infrastructure installations.',
                'brand' => 'Kyodo',
                'available_at' => ['hq', 'kuantan', 'balok', 'batu', 'chukai'],
                'variants' => ['Pipe GI', 'Pipe Colour', 'BS31 GI', 'BS31 Colour', 'MS61386 GI', 'MS61386 Colour', 'BS4568'],
                'sizes' => ['3/4" x 10ft', '1" x 10ft', '3/4" x 12.5ft', '1" x 12.5ft', '20mm x 10ft', '25mm x 10ft', '20mm x 12.5ft', '25mm x 12.5ft'],
                'choices' => ['SIRIM', 'JKR', 'GI', 'Colour Coated'],
                'inventory_matrix' => [],
            ],
            [
                'name' => 'Metal Trunking (MS IEC 61084 Type 1)',
                'category' => 'Industrial',
                'price' => 58.00,
                'rating' => 5,
                'image' => '/pdf-images/page-098-1.png',
                'description' => 'Indoor epoxy powder-coated and outdoor hot-dipped galvanized trunking with full accessory ecosystem.',
                'brand' => 'Smart',
                'available_at' => ['hq', 'kuantan', 'balok', 'batu', 'chukai'],
                'sizes' => ['2x2', '2x3', '2x4', '2x6', '2x8', '2x10', '2x12', '2x14', '3x3', '3x4', '3x6', '3x8', '3x10', '3x12', '4x4', '4x6', '4x8', '4x10', '4x12', '6x6', '6x8', '6x10', '6x12', '6x14', '6x16'],
                'types' => ['Epoxy Powder Coated (Class 1)', 'Hot Dipped Galvanized (Class 2)'],
                'choices' => ['18G', '15G', '14G', 'JKR Type 1'],
                'inventory_matrix' => [],
            ],
            [
                'name' => 'Cable Tray (SuperDyma / HDG / Standard)',
                'category' => 'Industrial',
                'price' => 96.00,
                'rating' => 5,
                'image' => '/pdf-images/page-100-1.png',
                'description' => 'Corrosion-resistant cable tray systems for indoor/outdoor routing with multiple widths and finishes.',
                'brand' => 'SuperDyma',
                'available_at' => ['hq', 'kuantan', 'balok', 'batu', 'chukai'],
                'variants' => ['SuperDyma 18G', 'HDG 18G', 'Standard'],
                'sizes' => ['2in x 2.44m', '3in x 2.44m', '4in x 2.44m', '5in x 2.44m', '6in x 2.44m', '8in x 2.44m', '10in x 2.44m', '12in x 2.44m'],
                'choices' => ['Indoor & Outdoor', 'Low Maintenance', 'High Corrosion Resistance'],
                'inventory_matrix' => [],
            ],
        ];

        $pageCatalogPath = base_path('../data/pdf_page_products.json');
        if (file_exists($pageCatalogPath)) {
            $pageCatalog = json_decode(file_get_contents($pageCatalogPath), true) ?? [];

            foreach ($pageCatalog as $item) {
                if (!is_array($item) || empty($item['name'])) {
                    continue;
                }

                $products[] = [
                    'name' => $item['name'],
                    'category' => $item['category'] ?? 'Industrial',
                    'price' => isset($item['price']) ? (float) $item['price'] : 0,
                    'original_price' => isset($item['originalPrice']) ? (float) $item['originalPrice'] : null,
                    'rating' => isset($item['rating']) ? (int) $item['rating'] : 4,
                    'image' => $item['image'] ?? '/pdf-images/page-001-1.png',
                    'description' => $item['description'] ?? 'PDF catalog reference entry.',
                    'is_new' => (bool) ($item['isNew'] ?? false),
                    'is_sale' => (bool) ($item['isSale'] ?? false),
                    'brand' => $item['brand'] ?? 'Focus Electrical',
                    'available_at' => $item['availableAt'] ?? ['hq'],
                    'variants' => $item['variants'] ?? [],
                    'colors' => $item['colors'] ?? [],
                    'sizes' => $item['sizes'] ?? [],
                    'lengths' => $item['lengths'] ?? [],
                    'types' => $item['types'] ?? [],
                    'choices' => $item['choices'] ?? [],
                    'model_codes' => $item['modelCodes'] ?? [],
                    'inventory_matrix' => $item['inventoryMatrix'] ?? [],
                ];
            }
        }

        foreach ($products as $item) {
            Product::updateOrCreate(
                ['name' => $item['name']],
                $item
            );
        }
    }
}
